### ISSUE TITLE
Version 2 is not listed on the StreamDeck Plugin Store

### ISSUE THREAD

**Issue by drewchurch** [CZDanol/StreamDeck-DiscordVolumeMixer2#1]
As the title states, the version 2 is not listed on the plugin store.

Running Stream Deck 6.0.2.17735 on Windows 11.

![image](https://user-images.githubusercontent.com/56129551/210006210-7a5aa437-6e32-41a4-a832-650fe6c0ce9f.png)

**Comment by CZDanol** [comment]
This is intentional. I've released the new version only unofficially for now so that people can find and report bugs. I'll release it in the marketplace later.

**Comment by drewchurch** [comment]
May I suggest mentioning that in the README? I only opened this issue as it wasn’t mentioned there. On Dec 30, 2022, at 01:09, Danol ***@***.***> wrote:﻿
This is intentional. I've released the new version only unofficially for now so that people can find and report bugs. I'll release it in the marketplace later.

**Comment by CZDanol** [comment]
Okay, done.
