### ISSUE TITLE
Discord settings don't load when opening stream deck

### ISSUE THREAD

**Issue by JuggleGod** [CZDanol/StreamDeck-DiscordVolumeMixer2#12]
I've installed and put in all the details for the Discord settings and it works just fine immediately after I put in the details. However, when I open the stream deck program a second time, after a restart, or whatever, there is no information in the discord settings and it just says something like "loading" and it never moves from there. If I just replace the button (which can be any of the buttons, they all have the same problem), the settings pop back up and everything works fine

**Comment by CZDanol** [comment]
Hello, please come to our Discord for troubleshooting.
