### ISSUE TITLE
Issue (I think?) with duplicate Discord user when not using the DVM profile

### ISSUE THREAD

**Issue by seriosbrad** [CZDanol/StreamDeck-DiscordVolumeMixer2#13]
When I manually assign "[DVM] Voice channel member" to dials, and not enough users are online to populate them all, a single user clones into each dial.  

![xnwI4PY](https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/assets/967695/93953790-0d78-42b9-9f4f-56440d26ce6a)

**Comment by CZDanol** [comment]
You gotta set up the "User index" field: 0 1 2 and 3
