### ISSUE TITLE
[Possible feature] Cycle between users

### ISSUE THREAD

**Issue by HamsterBBQ** [CZDanol/StreamDeck-DiscordVolumeMixer2#14]
Hi Danol,

I've been using this plugin and I was thinking that it would be a great idea to be able to cycle between users when you tap the screen or press the dial button.

Right now both tapping and pressing are doing the same action, which is mute the user, so we can use a lot of space with this feature.

I would appreciate so much if you will add this feature when you have some time.

Thank you so much,
Toni

**Comment by CZDanol** [comment]
Hello,
I've been already thinking about this. My current opinion is that you'd need an action to see the number of pages anyway, so it wouldn't really save anything in terms of display real estate. The feature to configure what the actions do could still be potentially added though. I'm open to opinions about this.

**Comment by CZDanol** [comment]
And how would you indicate that there are more users in the channel and how many?

**Comment by CZDanol** [comment]
Also to add, you can already have a single dial in the current implementation. You just need to reconfigure the paging buttons to offset 1 instead of 4 and it will normally work. You can even use a single paging button instead of two.

**Comment by CZDanol** [comment]
Added in the newest version in this repo. Please test it out and report if it works properly. If yes, I'll release it officially.

**Comment by CZDanol** [comment]
Hello, any updates?
