### ISSUE TITLE
Volume Control for Stream/Live

### ISSUE THREAD

**Issue by TheGuruAU** [CZDanol/StreamDeck-DiscordVolumeMixer2#15]
I only just installed this, and it looks great so far.

When a participant in a call has 'gone live' or is streaming, there is a separate volume control and muting available in native discord; but it seems like it does not show up in this plugin?

**Comment by CZDanol** [comment]
Hello, there are no bindings in the Discord RPC protocol for that, so I'm unable to implement that: https://discord.com/developers/docs/topics/rpc
