### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by SmashedSYSTEM** [CZDanol/StreamDeck-DiscordVolumeMixer2#17]
Followed all of the steps for troubleshooting  non of them worked for me how do I get pass this point?

![image](https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/assets/139532254/dea6df2c-c62c-4e4a-99b1-19d90100fea6)

**Comment by CZDanol** [comment]
Please visit our discord server for support like this.
