### ISSUE TITLE
ERR 8, app name on Discord developer portal

### ISSUE THREAD

**Issue by SquareBX** [CZDanol/StreamDeck-DiscordVolumeMixer2#26]
Until now, I've been making and using it well according to the manual, but at some point it didn't work with ERR 8. 
The way to fix this is because the app name >Discord Volume Mixer< produced by the Discord Developer Portal 
has the name >Discord<, so it doesn't work and it shows ERR 8. 

I changed the app name >Discord Volume Mixer< to >D Volume Mixer< unlike the example text and confirmed that it works normally.

I would like you to change the example app name (Discord Volume Mixer) to another example in the manual.

I truly appreciate your hard work.
I'm using it really well, thank you.
(written with translator)

![화면 캡처 2024-06-29 180313](https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/assets/75881474/e1c08143-ba91-4dfd-913c-8df013804ccc)

**Comment by CZDanol** [comment]
Hey, thanks for the info. I have changed it in the readme and asked the guys on the discord to try it out :)
