### ISSUE TITLE
Still getting Err 8 - nothing helps. FIXED - READ!

### ISSUE THREAD

**Issue by bytorphoto** [CZDanol/StreamDeck-DiscordVolumeMixer2#31]
Still getting Err 8, sometimes Err 2 and Err 4, but nothing I've tried is fixing it. I've tried ALL the suggestions (yes, ALL of them) from the install guide and previous Err 8 threads [here](https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/issues/27) and [here](https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2/issues/30) to no avail.

I know the Dev is busy and can't help just now. No blame, life gets busy sometimes.

Does ANYONE have a definitive fix for this that will work?

Thanks.

**Comment by Alex-Lee-Myers** [comment]
I am having the same issues. I tried everything suggested twice-over with no fix in sight. Hopefully someone can come up with something here.

**Comment by bytorphoto** [comment]
OK, an update. Despite the crap that I got from previous "helpers" I decided to work on this myself and I've found out a fix for my problem.

1. I DID NOTHING WRONG IN THE SET UP!

2. I followed the instructions exactly. Including item 4. which states you can name the bot anything you like, as long as you don't include the word Discord in it... 

3. I named my bot originally "SDDVolumeMixer" and it failed, despite every setting being correct.

4. The solution? SPACES! I changed NOTHING but the name and changed it to "SDD Volume Mixer" and it works.

My guess is that, after a certain number of characters, capitals or whatever, the authentication process fails, so without the spaces in mine, it would never work. I even tried "DVol" but it worked, so I guess having 4 caps in a row, or something broke the extention, authentication, or whatever, so to those volunteers who claimed it was all my fault and I'd done something wrong or not configured the plugin right, I TOLD YOU YOU WERE WRONG. HERE'S THE PROOF.


I hope this helps some other person who's being called an idiot by the volunteers, and maybe you'll listen to someone when they tell you they've followed the instructions properly, in future. And stop being so arrogant about it.

**Comment by Ayla-jn** [comment]
life saver! i had the same problem, i did everything right and still got the err8 and changing the same so 'DVol' worked for me, so happy its fixed now

**Comment by saarlac** [comment]
I've had this installed and working for a long time. Suddenly I have the same issues with err 8 too I have reinstalled everything, changed the name as suggested several times. I just don't get it.

**Comment by bytorphoto** [comment]
Guess I spoke too soon... overnight, the issues came back, now it's unusable, so I'm just deleting it. The Dev is apparently too busy to keep it going, so unless someone else does, it's effectively dead.
