### ISSUE TITLE
No Avatars Displayed on Stream Deck MK.2

### ISSUE THREAD

**Issue by djsleahy** [CZDanol/StreamDeck-DiscordVolumeMixer2#4]
Inside the default profile, no user avatars or other identifiers are displayed.

Screenshot attached.

All other functionality seems to behave as intended.

![image](https://user-images.githubusercontent.com/27892653/211118455-9dae9435-f532-4056-b050-af66c9508b1d.png)

**Comment by DuffyScottC** [comment]
Are you in a voice call with other people during this screenshot?

**Comment by CZDanol** [comment]
By the "Discord Volume Mixer copy" name, seems like you have a bit of a mess in the profiles. Try deleting all Discord Volume Mixer profiles, the application should install a new one after clicking on the DVM main button. Check if that fixes the things,

**Comment by djsleahy** [comment]
Deleted all relevant profiles and reinstalled. No change.

In a call with approx 6 others if I recall correctly. Retested after above in a call consisting of 4 others.

**Comment by michael1179088** [comment]
I am having the same issues

**Comment by CZDanol** [comment]
Would any of you be willing to let me have a look on that via Teamviewer?

**Comment by djsleahy** [comment]
Hi folks, I updated StreamDeck Software version to the most recent available (6.0.2.17735).

Updated StreamDeck Firmware version to latest version 1.00.003.

This has fixed the issue.

I never noted the versions prior to the updates. But this package is obviously not compatible with older versions. Apologies for the confusion.

For @michael1179088 (Please note the existing version of both software and firmware prior to updating and post them here for debugging purposes): 
1) Open Stream Deck application.
2) Click the cog icon.
3) Click 'Check for Updates'.
4) complete the update Process.
5) Once the update process completes you may need to reopen the Stream Deck application.
6) Click the cog icon again.
7) Next to 'Firmware Version' you should see an update option (This option disappears after the update).
8) Complete the update procedure.
