### ISSUE TITLE
What does the back button do?

### ISSUE THREAD

**Issue by sephentos** [CZDanol/StreamDeck-DiscordVolumeMixer2#5]
What does the back button do?
Nothing happens when I press on it. I was expecting that it returns me to my default steam deck profile.
If its not intended for that I'd add a regular profile switching button of the steam deck itself.

(Using the newest version of your plugin)

![image](https://user-images.githubusercontent.com/35430448/215302473-60005f63-aa49-4c11-8de8-7ee153c829ab.png)

**Comment by CZDanol** [comment]
The button returns you to the previous profile you were on, assuming you've accessed the current profile by the "DVM Mixer" button or via profile switch. If you say accessed the profile from the Stream Deck software or loaded the software with the profile already on, the system doesn't know what profile to return to and does nothing.

**Comment by sephentos** [comment]
Ok, then I guess, it's not working for me.
I accessed the DVM profile (seen as in the screenshot) via the DVM Mixer button but the return button does nothing for me.
It does not return me to my default profile (which is the only profile existing aside the DVM profile).
And yes, I was on my default profile before.

If I can help you debugging let me know.

**Comment by CZDanol** [comment]
I'd start with removing the DVM profiles from the deck and letting the system automatically install them - from the screenshot, it seems that you have multiple of them.

**Comment by sephentos** [comment]
That's exactly what I've tried several times.
I've even uninstalled and reinstalled the plugin multiple times, but it always automatically creates the DVM profile with "copy" in the name. It never creates a profile without "copy" in the name.
Of course, before each test, I deleted all profiles except the default profile

**Comment by sephentos** [comment]
Yes, seems to me to be a bug in the Stream Deck software as well.
I only explained it in case you are interested, or whatever. :-) 

Added my own profile switch button for me now.
Thanks anyway.
