### ISSUE TITLE
BUG: When getting moved "Nobody in voice chat" is shown (Stream Deck +)

### ISSUE THREAD

**Issue by DJKnaeckebrot** [CZDanol/StreamDeck-DiscordVolumeMixer2#6]
When you get moved from a channel the plugin will break and wont show users in the channel.

Fixable by rejoining the channel so I asume the new channelId is not passed/processed.

**Comment by CZDanol** [comment]
Thanks for the report. Does it mean that this happens only when you get moved by admin/something else? Or when you move between channels by yourself?

**Comment by DJKnaeckebrot** [comment]
Have tested it with only being moved, switchting the channel usually fixed it for me. 

I'll do some more testing and will let you know.

**Comment by DJKnaeckebrot** [comment]
Ok moved myself and its not showing anymore. :)

**Comment by DJKnaeckebrot** [comment]
Oh with move i mean drag and drop or right click and move to not clicking on a different channel

**Comment by CZDanol** [comment]
I'll look into that, might take a while till I get free time for that though.

**Comment by DJKnaeckebrot** [comment]
No Problem, its not breaking it and can be fixed "pretty" easy :) Thanks for looking into it !

**Comment by CZDanol** [comment]
Fixed.
