### ISSUE TITLE
Profile Pictures not showing

### ISSUE THREAD

**Issue by nefariouslegion** [CZDanol/StreamDeck-DiscordVolumeMixer2#7]
When using this plugin it used to show the profile pictures of whoever was in the discord voice channel with me. Now it's just blank so I don't know whose volume the buttons control. 
![image](https://user-images.githubusercontent.com/89366675/216789441-322d3caf-a235-4eea-bca2-3447485e1e23.png)

**Comment by CZDanol** [comment]
Read https://github.com/CZDanol/StreamDeck-DiscordVolumeMixer2#common-problems.

**Comment by nefariouslegion** [comment]
Yeah sorry found that after I posted. Fixed now thank you
