### ISSUE TITLE
Volume goes automatic to 200%

### ISSUE THREAD

**Issue by ITElite22** [CZDanol/StreamDeck-DiscordVolumeMixer2#9]
Dont know why.... but since an update of stream deck+ i think. The peoples in Discord turns automaticly to 200%  after i restart my pc or open the app to the first time. i dont do anything. it goes automatic... dont know why. Can you  help?

Edit: everytime after i muted them. it goes to 200%

**Comment by CZDanol** [comment]
Hello, does the problem still persist? Please visit our discord for troubleshooting.
